language: node_js
node_js:
- '8'
env:
  global:
  - REACT_APP_RELEASE=$TRAVIS_COMMIT
  - HEROKU_APP_ID=ancient-hamlet-42126
  - SENTRY_ORG=testorg-az
  - SENTRY_PROJECT=sentry-demo
  - secure: p2OkLEcyf7z4TQyPAzJiyjoR4SdyavT7/bmIKEtpNtAj2otiU6wIyBoKZ7MjOEUxffcZzHEmP2+44u1x25Q7ozrH3PUHYxJkBWP+mQiZxtt+1J157q24r6+9WL6uaRVabwQhigPpRwXEntIvoJuAHgp+X1+TP/jWuux/yQA2SivEg/O7l2FqUqeBcXzUMLzEOP+pAx4NPVTAnguPnHsSwxIJw/W1C6lzqzxY4q1aysJbblHLKXnRhIHJSPBqxgYK8Db00gFKpSpzUCHMCFVlZURBw+OLA8Tih2LSLAZ7YfYQlVlu+vkMGuArJ2coE1drk3os/F+SbiJ8rNhqi3wnvZUf9Muf0lPRjuB70xlD8jM6J+lWYhqABsCx3UvWNN7cmKXxb+xtvWZT1ItbVMeVq17OT1v7UdfbsRp6Z2keo2ctjj041s9t54Qen+PsM5oczpXyDxRJt7j8CzTvrWUMJXEobhxTkcV0vULIzpeWB1KzE2TXK6gguTJdDVAAESACB9LJ2Lq+cDFrLbBzdk97rjpfcCEfRPQkLXA4Qoft7yFu6Nuu0zmA+jeczaPXNpSNegBg/YMHoTTKIrDYZNTqgJR7E9JUki3WA2ByBRvR8Eo9xgkRjrpYfAI9KW58ZiWDcoSsXKtLyVDRQUkfIczsuTSog2uD3roRDO3i2mBMfvg=
  - secure: LG3oZsEJWd7ZYvOidTpfj/583id2XRYuDbn0nxBEjA+72zUXE5EOppOUTW9DkDyuzLgfjnq5IC11SkHtKfjSpEY+bffiPDbVcuXbArR6/JYD2EuvawGh4WAc1CPdCcrcVfUKz/rdn4S/CbJ1nXNAxKisZf86yO7kGj7CIRhlRFH9JInlJNfahWsoG4IAMIOHaFGxaS7KM+8PnllFFqrrpX9dhZ+eHBmu5gbJhZ7tOJM0i4GwXHJe7ecizJ4tGNLdrXYKKRDbX6YW1QzClKO2Lt9uOai0lYdQ5MPKgDm3zAFmM4dxAQ4U5qyA+vXSn8sZbSYzT3dxDuj79tQfQuHlhn3z2Rh0NLlScDII29NbMACgQJ0JfrH6wKa2FxZlzFNu24we1mg0So78w56ksCiV7WWSGZBTyGhEvz944ZVy8YwLb8xWcRXwCeUgwIf1monv0eL2AZS959byjW/ws5TV9cJ0qDnRJmk8Ur7vmmXJngn8o4eBbW+1nY/5nxAbJ0ZpniK7KT6WzVZH+Uvdop7VVq3PoQLwOwfGnvmFpTuCm2y4TUTrkkxlsQqBvTagu8q4BKOKvzUXTC6kAnuUUfFp1ubyUpBP3AGNFAhGDBTARJmTj9Buxp59+jshkvxTxOwY65Bdv0nJwvQUDfnSmw/0wXlKoBn8a9RdwQA++vTkOik=
before_install:
- npm install -g sentry-cli-binary
deploy:
  provider: heroku
  api_key:
    secure: fjabKZ+pPGAbCZGkgLoaozlW0oyyRn7Ri+63r3gTGhqxkQ0mfLoqhBnbCRUo6c2EAUmMB2i3XGQgKRN4Y9w7gnJF44OeUqSHOrLvKYWw/fW5sDcp1wGJ2RwsMEfFrSgkw0vwecxsarUoQCzLnR6eGxlxLcKd2oAle2G18kKFPr1t35buzqzqVdLE+knApndWswZyWyz0hFT83EIFIbvA4yQBNUxBGGmpiKUbPZsa+2INPxnXJbAxJZXvoU2MlRxjSWbK7dGSdgYrf6zEhuUksbklisEniBPTwzMi0VjOT6oSGg03uHKvS3WRk9NIg7LHgnvI4fqMQoQqT9QEV95UqS+YpqqTRMwz4A8ZgKeuxRFJiY8tROuzdg8rH2Ay+ykDX021a0+SknUvIJdDKLqIxQtZT1DWObvRrVMKmZdzmggeWKAlzd+h44fOUSd2oZlmdcg2Cu9+FVej8r1eFVVP/KhfMKB8z+qmY0gJ/HFhosiKCRvBM1Oth1Pcp9jy9H0ioaQxAhggK550du1vGXXMxBtfEkcCkezMdDuMvGASaB0a+rJKxJRobuVYc2frN2HhZt+VxRe4hNBPWmtAKZtcN7CgyNo1OHotnp23x0BlzYFdF+hZxkIj2hgCgQGCnAG/nVJw0jJSB0/0TpNwFcwoQdRsUZgLMtK/WFJ04dqSn4A=
  app: ancient-hamlet-42126
  on:
    repo: ndmanvar/sentry_demo
before_deploy:
- ls . && printenv && hostname && make release
