language: node_js
node_js:
- '8'
env:
  global:
  - REACT_APP_RELEASE=$TRAVIS_COMMIT
  - HEROKU_APP_ID=sentry-react-demo
  - SENTRY_ORG=testorg-az
  - SENTRY_PROJECT=sentry-react-demo
  - secure: p2OkLEcyf7z4TQyPAzJiyjoR4SdyavT7/bmIKEtpNtAj2otiU6wIyBoKZ7MjOEUxffcZzHEmP2+44u1x25Q7ozrH3PUHYxJkBWP+mQiZxtt+1J157q24r6+9WL6uaRVabwQhigPpRwXEntIvoJuAHgp+X1+TP/jWuux/yQA2SivEg/O7l2FqUqeBcXzUMLzEOP+pAx4NPVTAnguPnHsSwxIJw/W1C6lzqzxY4q1aysJbblHLKXnRhIHJSPBqxgYK8Db00gFKpSpzUCHMCFVlZURBw+OLA8Tih2LSLAZ7YfYQlVlu+vkMGuArJ2coE1drk3os/F+SbiJ8rNhqi3wnvZUf9Muf0lPRjuB70xlD8jM6J+lWYhqABsCx3UvWNN7cmKXxb+xtvWZT1ItbVMeVq17OT1v7UdfbsRp6Z2keo2ctjj041s9t54Qen+PsM5oczpXyDxRJt7j8CzTvrWUMJXEobhxTkcV0vULIzpeWB1KzE2TXK6gguTJdDVAAESACB9LJ2Lq+cDFrLbBzdk97rjpfcCEfRPQkLXA4Qoft7yFu6Nuu0zmA+jeczaPXNpSNegBg/YMHoTTKIrDYZNTqgJR7E9JUki3WA2ByBRvR8Eo9xgkRjrpYfAI9KW58ZiWDcoSsXKtLyVDRQUkfIczsuTSog2uD3roRDO3i2mBMfvg=
  - secure: jlypOnANosRmMfrRFV/4CNfg2hMUy7TK9ln5UXixlbtyVTgV3E9AH948HVP0nsUbf2m7y0P3BFsPwNCqyeFEhwK51QMevENIMzNroL8FLL/wykoRPmb731mV2afT4b02IHiXT4aqe3YUPhIZwDkVeGv0i8L2FPw5zihhP+cF/5MvSxSa8ourMkLN2cBdPK26NyyiYwCK71cRaU3a4ivmC2hy3BNMa4HoX6KtYCulmH9RExE9lp9fq68CCByqpuRPM/2pOB0Szcx21yIWwuyRLJdBBAkZ9TkPanne5w+ZdVF4v338zrPyfpuVaG0si0Dy7JI4npHWMMYSND9iUtePkcUHnRy79sYYXO0RbXX9pLs9sZhQ5T8+NWbItKpbP26gJomkT27BLrqebxUEi7fnV7qtvY2IuEBOcVDgz58ROIL1r8TQ/zxZysPj8SG656P4xf/g8LJSFJpGdt7tFBY9MBIawJL/um0BC0GZ2ybazy6SGu4XzQOIy0ycOuRqlhp08NHCfmbXRtgRSoXNujudaRQARDiGoJOe2UqRljr9yfD+c1SQcCUJWep/IycuMQqr18nF2urZv3EmkZo9MrAqmaP/3kzy6DLI6pyU/gsEv4SbTEjjSUTQGJ6Q1/cOCmQTi5DN9/NnhoIDL722l6bp8T4P5GPwYKWn6LylBbKZ7eI=
before_install:
- npm install -g sentry-cli-binary
deploy:
  provider: heroku
  api_key:
    secure: ZWDuXdmmINfGxWckeL0iURxJDFXUVr6TVzWANR1anN0mL0S/sD1zYP+16MMw7iN7jPvbSPcx1YtZlIblnxzhuhRjjuBfHVwi4JiUl2ssR+aRWPD/zyaFPkkfv7KkYHE1TkpLD9rBjkaudzDrDy+YecMckWAmwR/vsw+JiSwoFQKcnIHJ1FPdtGjkEnyTyDsxT0hYvYUn7GV0+hU6pN1wSyLyZw9K6PC1eTLXBpqXl8qfmIdtYmVhw03JD3uD2WoLARK5N71Xphh08/SfIj4MBo9+hYTZTRhiGK+89B5qjnKdT0jBZoxHG2q7+NdC9KakArtM4zf3N+YSn9amXiUGEsRCK5npx3Ol5WjiRqNTl1g6U+vbRwJf1blSmijNPRe9MQ0gF0C8gqxhaknkJ/Ciuc9V9lL454xJbNKyoveS6y7axeuySsG11Y09IWMRlemYhgak2itInzN/RmDA/k0fPyZW+hdP3vgcCoX85d5LbR5K5seYzzsDVR/xaSfHHM5lyBu7ylUoyvl/5s7IWGO7E469qCkN6OaC1CP0nx8MPP1VpUe5FYoKfQ7nnw6WIrebrV7gWn0/L1OPUdnzMA0cdSX5eLYw7TfQFXGrAz64og6WrVpwfnJbjWrFJgxGcwG4b1BPNhqwMHSNBB+AL0Wdx1He2NunLlCUw2gDe7e0ew4=
  app: sentry-react-demo
  on:
    repo: ndmanvar/sentry-demo
before_deploy:
- make setup_release
